name: Run build on push
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache intellij download
        uses: actions/cache@v2.1.3
        with:
          path: lib/download
          key: intellij-${{ hashFiles('gradle/dependencies.gradle') }}
      - name: Cache gradle
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -i
      - uses: actions/upload-artifact@v2
        with:
          name: reports-${{ matrix.os }}
          path: ${{ github.workspace }}/build/reports/**/*
      - uses: actions/upload-artifact@v2
        with:
          name: release-${{ matrix.os }}
          path: ${{ github.workspace }}/build/bin/native/releaseExecutable/*
